"""empty message

Revision ID: 000f3ddc6d1d
Revises: 5adee4cfc6e4
Create Date: 2022-04-06 09:25:28.157449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '000f3ddc6d1d'
down_revision = '5adee4cfc6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('answer_ibfk_2', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['question_id'])
    op.drop_column('answer', 'questionFk_id')
    op.add_column('game', sa.Column('test_id', sa.Integer(), nullable=True))
    op.drop_constraint('game_ibfk_1', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'test', ['test_id'], ['test_id'])
    op.drop_column('game', 'testFK_id')
    op.add_column('partida', sa.Column('game_id', sa.Integer(), nullable=True))
    op.drop_constraint('partida_ibfk_2', 'partida', type_='foreignkey')
    op.create_foreign_key(None, 'partida', 'game', ['game_id'], ['game_id'])
    op.drop_column('partida', 'gameFK_id')
    op.add_column('question', sa.Column('test_id', sa.Integer(), nullable=True))
    op.drop_constraint('question_ibfk_1', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'test', ['test_id'], ['test_id'])
    op.drop_column('question', 'testFK_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('testFK_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_ibfk_1', 'question', 'test', ['testFK_id'], ['test_id'])
    op.drop_column('question', 'test_id')
    op.add_column('partida', sa.Column('gameFK_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'partida', type_='foreignkey')
    op.create_foreign_key('partida_ibfk_2', 'partida', 'game', ['gameFK_id'], ['game_id'])
    op.drop_column('partida', 'game_id')
    op.add_column('game', sa.Column('testFK_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_ibfk_1', 'game', 'test', ['testFK_id'], ['test_id'])
    op.drop_column('game', 'test_id')
    op.add_column('answer', sa.Column('questionFk_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_ibfk_2', 'answer', 'question', ['questionFk_id'], ['question_id'])
    op.drop_column('answer', 'question_id')
    # ### end Alembic commands ###
