"""empty message

Revision ID: 16053601212b
Revises: cd273b3136ff
Create Date: 2022-04-05 15:08:29.646124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16053601212b'
down_revision = 'cd273b3136ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partida',
    sa.Column('par_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('timeStamp', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('par_id')
    )
    op.drop_table('resultado')
    op.add_column('user', sa.Column('manager_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'manager_id')
    op.create_table('resultado',
    sa.Column('res_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('game', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('player_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['user.user_id'], name='resultado_ibfk_1'),
    sa.PrimaryKeyConstraint('res_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('partida')
    # ### end Alembic commands ###
