"""empty message

Revision ID: 5adee4cfc6e4
Revises: 6a71864f9b37
Create Date: 2022-04-06 08:31:27.080401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adee4cfc6e4'
down_revision = '6a71864f9b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('testName', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.add_column('game', sa.Column('testFK_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'test', ['testFK_id'], ['test_id'])
    op.add_column('question', sa.Column('testFK_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'test', ['testFK_id'], ['test_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'testFK_id')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'testFK_id')
    op.drop_table('test')
    # ### end Alembic commands ###
