"""empty message

Revision ID: 69b593271fc7
Revises: 000f3ddc6d1d
Create Date: 2022-04-20 08:35:03.426773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69b593271fc7'
down_revision = '000f3ddc6d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('scale_num', sa.Integer(), nullable=True))
    op.drop_column('answer', 'details')
    op.add_column('game', sa.Column('nivelAvanzado', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('nivelProceso', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('nivelInicial', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('game_id', sa.Integer(), nullable=True))
    op.drop_constraint('question_ibfk_1', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'game', ['game_id'], ['game_id'])
    op.drop_column('question', 'test_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('test_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_ibfk_1', 'question', 'test', ['test_id'], ['test_id'])
    op.drop_column('question', 'game_id')
    op.drop_column('game', 'nivelInicial')
    op.drop_column('game', 'nivelProceso')
    op.drop_column('game', 'nivelAvanzado')
    op.add_column('answer', sa.Column('details', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('answer', 'scale_num')
    # ### end Alembic commands ###
