"""empty message

Revision ID: 6a71864f9b37
Revises: b57b11534be1
Create Date: 2022-04-06 08:29:16.962298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a71864f9b37'
down_revision = 'b57b11534be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('questionFk_id', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'answer', 'question', ['questionFk_id'], ['question_id'])
    op.add_column('partida', sa.Column('gameFK_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'partida', 'game', ['gameFK_id'], ['game_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partida', type_='foreignkey')
    op.drop_column('partida', 'gameFK_id')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'user_id')
    op.drop_column('answer', 'questionFk_id')
    # ### end Alembic commands ###
