"""empty message

Revision ID: 97a40f73b06f
Revises: 69b593271fc7
Create Date: 2022-04-27 11:32:34.530493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a40f73b06f'
down_revision = '69b593271fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'code')
    op.drop_column('user', 'department')
    # ### end Alembic commands ###
