"""empty message

Revision ID: b57b11534be1
Revises: 16053601212b
Create Date: 2022-04-05 15:14:40.798087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57b11534be1'
down_revision = '16053601212b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameName', sa.String(length=255), nullable=True),
    sa.Column('habilidad', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.add_column('partida', sa.Column('player_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'partida', 'user', ['player_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partida', type_='foreignkey')
    op.drop_column('partida', 'player_id')
    op.drop_table('question')
    op.drop_table('game')
    op.drop_table('answer')
    # ### end Alembic commands ###
