"""empty message

Revision ID: c0fc722ab60c
Revises: c6185e18e52e
Create Date: 2022-04-04 10:17:15.857468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0fc722ab60c'
down_revision = 'c6185e18e52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultado',
    sa.Column('res_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('res_id')
    )
    op.drop_table('candidato')
    op.add_column('user', sa.Column('birthDate', sa.Date(), nullable=True))
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'birthDate')
    op.create_table('candidato',
    sa.Column('res_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('game', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('res_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('resultado')
    # ### end Alembic commands ###
